# -*- coding: utf-8 -*-
"""shrink_cv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t27vu3tCfyAt5iWRUaBYk0n5VimGZU6k
"""

# Commented out IPython magic to ensure Python compatibility.
import cv2 
import numpy as np 
import matplotlib.pyplot as plt  
# % matplotlib inline 
# This is a magic command to display in external window 
  
image = cv2.imread("/content/drive/My Drive/Colab Notebooks/hand_num.png", 0) 
# Loading the image 
  
shrunk = cv2.resize(image, (28, 28), interpolation = cv2.INTER_AREA) 
shrunk = np.array(shrunk)
np.savetxt("/content/drive/My Drive/Colab Notebooks/test_imgdata.csv", shrunk, delimiter = ",")

#Titles =["Original", "Shrunk"] 
#images =[image, shrunk] 
#count = 2
  
#for i in range(count): 
#    plt.subplot(2, 2, i + 1) 
#    plt.title(Titles[i]) 
#    plt.imshow(images[i]) 
  
#plt.show()